package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"html"
	"io"
	"net"
	"net/http"
	"net/url"
	"sort"
	"strings"
	"time"
)

const (
	authEndpoint  = "https://accounts.google.com/o/oauth2/v2/auth"
	tokenEndpoint = "https://oauth2.googleapis.com/token"
	driveScope    = "https://www.googleapis.com/auth/drive"
	redirectURI   = "https://music.ser1ka.com/oauth/google/callback"
	callbackPath  = "/oauth/google/callback"
	// The landing server on :8080 (behind the tunnel) forwards /oauth/ here.
	callbackListen = "127.0.0.1:8081"
)

type oauthClient struct {
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}

func loadClient() (oauthClient, error) {
	var f struct {
		Web oauthClient `json:"web"`
	}
	if err := loadJSON(clientFile, &f); err != nil {
		return oauthClient{}, err
	}
	if f.Web.ClientID == "" || f.Web.ClientSecret == "" {
		return oauthClient{}, errors.New("client file has no web.client_id / web.client_secret")
	}
	return f.Web, nil
}

type token struct {
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	Expiry       time.Time `json:"expiry"`
	Scope        string    `json:"scope"`
	ObtainedAt   time.Time `json:"obtained_at"`
	// RefreshTokenExpiresIn is only sent while the OAuth app is in "Testing" (7-day refresh tokens).
	RefreshTokenExpiresIn int `json:"refresh_token_expires_in,omitempty"`
}

// exchange calls the token endpoint and also returns the response's field names,
// so the presence of refresh_token_expires_in is visible without printing secrets.
func exchange(ctx context.Context, c oauthClient, form url.Values) (token, []string, error) {
	form.Set("client_id", c.ClientID)
	form.Set("client_secret", c.ClientSecret)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, tokenEndpoint, strings.NewReader(form.Encode()))
	if err != nil {
		return token{}, nil, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return token{}, nil, err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	var m map[string]any
	if err := json.Unmarshal(body, &m); err != nil {
		return token{}, nil, fmt.Errorf("token endpoint %d: unreadable response", resp.StatusCode)
	}
	if resp.StatusCode != http.StatusOK {
		return token{}, nil, fmt.Errorf("token endpoint %d: %v %v", resp.StatusCode, m["error"], m["error_description"])
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	str := func(k string) string { s, _ := m[k].(string); return s }
	num := func(k string) int { n, _ := m[k].(float64); return int(n) }
	now := time.Now()
	return token{
		AccessToken:           str("access_token"),
		RefreshToken:          str("refresh_token"),
		Scope:                 str("scope"),
		Expiry:                now.Add(time.Duration(num("expires_in")) * time.Second),
		ObtainedAt:            now,
		RefreshTokenExpiresIn: num("refresh_token_expires_in"),
	}, keys, nil
}

func cmdAuth(ctx context.Context, args []string) error {
	fs := flag.NewFlagSet("auth", flag.ExitOnError)
	hint := fs.String("login-hint", "phsub350@gmail.com", "account to preselect on the Google sign-in page")
	wait := fs.Duration("wait", time.Hour, "how long to wait for the browser callback")
	pasted := fs.String("callback-url", "", "finish with a callback URL copied from the browser (when the listener was not running)")
	fs.Parse(args)

	client, err := loadClient()
	if err != nil {
		return err
	}
	st, err := loadState()
	if err != nil {
		return err
	}
	if *pasted != "" {
		return finishPasted(ctx, client, st, *pasted)
	}
	nonce := make([]byte, 16)
	if _, err := rand.Read(nonce); err != nil {
		return err
	}
	expected := hex.EncodeToString(nonce)
	// Persist the state so a callback URL can still be completed with -callback-url
	// if this listener dies before the browser comes back.
	st.PendingAuthState = expected
	if err := st.save(); err != nil {
		return err
	}

	q := url.Values{
		"client_id":     {client.ClientID},
		"redirect_uri":  {redirectURI},
		"response_type": {"code"},
		"scope":         {driveScope},
		"access_type":   {"offline"},
		"prompt":        {"consent"},
		"state":         {expected},
		"login_hint":    {*hint},
	}

	type result struct {
		code string
		err  error
	}
	done := make(chan result, 1)
	mux := http.NewServeMux()
	mux.HandleFunc("GET "+callbackPath, func(w http.ResponseWriter, r *http.Request) {
		v := r.URL.Query()
		// Only the state generated by this run is accepted, so a stray or forged callback
		// cannot plant someone else's token.
		if v.Get("state") != expected {
			http.Error(w, "invalid state", http.StatusBadRequest)
			return
		}
		if e := v.Get("error"); e != "" {
			writePage(w, "授權未完成", "Google 回傳："+e)
			select {
			case done <- result{err: fmt.Errorf("authorization failed: %s", e)}:
			default:
			}
			return
		}
		code := v.Get("code")
		if code == "" {
			http.Error(w, "missing code", http.StatusBadRequest)
			return
		}
		writePage(w, "授權完成", "ser1ka Music 已取得授權，可以關閉這個頁面。")
		select {
		case done <- result{code: code}:
		default:
		}
	})
	ln, err := net.Listen("tcp", callbackListen)
	if err != nil {
		return fmt.Errorf("listen %s: %w", callbackListen, err)
	}
	srv := &http.Server{Handler: mux, ReadHeaderTimeout: 10 * time.Second}
	go srv.Serve(ln)
	defer srv.Shutdown(context.Background())

	fmt.Printf("Open this URL and sign in as %s:\n\n%s?%s\n\nwaiting for the callback (up to %s)...\n", *hint, authEndpoint, q.Encode(), *wait)

	var res result
	select {
	case res = <-done:
	case <-time.After(*wait):
		return errors.New("timed out waiting for the callback")
	}
	if res.err != nil {
		return res.err
	}

	return finishCode(ctx, client, st, res.code)
}

func finishPasted(ctx context.Context, client oauthClient, st *state, raw string) error {
	u, err := url.Parse(raw)
	if err != nil {
		return err
	}
	v := u.Query()
	if st.PendingAuthState == "" || v.Get("state") != st.PendingAuthState {
		return errors.New("state in the URL does not match the pending authorization; run `auth` again")
	}
	if e := v.Get("error"); e != "" {
		return fmt.Errorf("authorization failed: %s", e)
	}
	if v.Get("code") == "" {
		return errors.New("no code in the URL")
	}
	return finishCode(ctx, client, st, v.Get("code"))
}

func finishCode(ctx context.Context, client oauthClient, st *state, code string) error {
	tok, keys, err := exchange(ctx, client, url.Values{
		"grant_type":   {"authorization_code"},
		"code":         {code},
		"redirect_uri": {redirectURI},
	})
	st.PendingAuthState = "" // codes are single-use either way
	if serr := st.save(); serr != nil && err == nil {
		err = serr
	}
	if err != nil {
		return err
	}
	if tok.RefreshToken == "" {
		return errors.New("no refresh_token in the response")
	}
	if err := saveJSON(tokenFile, tok); err != nil {
		return err
	}
	fmt.Printf("token saved to %s (0600)\n", tokenFile)
	fmt.Printf("token response fields: %s\n", strings.Join(keys, ", "))
	fmt.Printf("granted scope: %s\n", tok.Scope)
	if tok.RefreshTokenExpiresIn > 0 {
		fmt.Printf("refresh_token_expires_in=%d → the app is still in Testing; the refresh token expires in %.1f days\n",
			tok.RefreshTokenExpiresIn, float64(tok.RefreshTokenExpiresIn)/86400)
	} else {
		fmt.Println("no refresh_token_expires_in → the app is In production; the refresh token has no 7-day limit")
	}
	return cmdAbout(ctx, nil)
}

func writePage(w http.ResponseWriter, title, msg string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprintf(w, `<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>%[1]s</title><body style="font:16px/1.6 system-ui,sans-serif;max-width:32rem;margin:3rem auto;padding:0 1rem">
<h1>%[1]s</h1><p>%[2]s</p></body>`, html.EscapeString(title), html.EscapeString(msg))
}
